name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make env.prod
      run: |
        bash scripts/make_env_prod.sh
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Build and publish app image to GCR
      uses: carbonchain/action-container-registry@v1.4
      with:
        project_id: wind-curtailment
        dockerfile: ./Dockerfile
        target: app
        image: gcr.io/wind-curtailment/app
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Deploy app to Cloud Run
      uses: stefda/action-cloud-run@v1.6
      with:
        image: gcr.io/wind-curtailment/app
        service: wind-curtailment-app
        project: wind-curtailment
        region: europe-north1
        env: ./env/.env.prod
        service key: ${{ secrets.GCLOUD_AUTH }}

    - name: Build and publish etl image to GCR
      uses: carbonchain/action-container-registry@v1.4
      with:
        project_id: wind-curtailment
        dockerfile: ./Dockerfile
        target: etl
        image: gcr.io/wind-curtailment/etl
        service_account_key: ${{ secrets.GCLOUD_AUTH }}


    - name: Deploy ETL to Cloud Run
      uses: stefda/action-cloud-run@v1.6
      with:
        image: gcr.io/wind-curtailment/etl
        service: wind-curtailment-etl
        project: wind-curtailment
        region: europe-north1
        env: ./env/.env.prod
        service key: ${{ secrets.GCLOUD_AUTH }}
